apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  labels:
    app: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      name: portfolio-app
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: bimalpaudel/portfolio:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
