apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3000
      nodePort: 30002
  type: NodePort
